version: "2.3"
services:
  schafkopf-training:
    image: schafkopf-trainenv
    build:
      context: .
      dockerfile: TrainEnv.Dockerfile
    volumes:
      - "./model:/app/model"
      - "./logs:/app/logs"
    entrypoint: dotnet Schafkopf.Training.dll
